serviceAccount: "cloudbuild-runner-sa@smart-ad-451409.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # 1) Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/$PROJECT_ID/smart-ad-artifacts/smart-ad-api:$SHORT_SHA',
        '.'
      ]

  # 2) Docker 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/$PROJECT_ID/smart-ad-artifacts/smart-ad-api:$SHORT_SHA'
      ]

  # 3) Cloud Run 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'smart-ad-api',
        '--image=asia-northeast3-docker.pkg.dev/$PROJECT_ID/smart-ad-artifacts/smart-ad-api:$SHORT_SHA',
        '--region=asia-northeast3',
        '--platform=managed',
        '--set-secrets=DB_PASSWORD=projects/484753512912/secrets/DB_PASSWORD/versions/latest',
      ]

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/smart-ad-artifacts/smart-ad-api:$SHORT_SHA'